/**
 * 
 */
package server;

import java.io.IOException;
import java.rmi.AlreadyBoundException;

import org.jdom2.JDOMException;

import client.ClientRMIRemote;
import controller.ModelChange;

/**
 * @author Francesco Vetro'
 *
 */
public class ServerRMIRegistration implements ServerRMIRegistrationRemote {

	private Server server;
	
	/**
	 * constructor for the access point to all RMI views 
	 * to participate in the game ready on server
	 * @param server the server where this registration
	 * 					utility is operating
	 */
	public ServerRMIRegistration(Server server) {
		this.server = server;
	}
	
	/* (non-Javadoc)
	 * @see server.ServerRMIRegistrationRemote#register(client.ClientRMIRemote)
	 */
	/**
	 * @param client the RMI client that will be registered as a
	 * 					possible player
	 * @throws AlreadyBoundException 
	 * @throws JDOMException if file configuration generates errors
	 * @throws IOException if file configuration generates errors or if a
	 * 			RemoteException is generated by the remote method invocation
	 */
	@Override
	public ServerRMIViewRemote register(ClientRMIRemote client) throws AlreadyBoundException, JDOMException, IOException {
		ServerRMIView view = new ServerRMIView(client);
		server.addClient(view);
		view.update(new ModelChange(server.getGame()));
		return view;
	}

}
